import { PROVIDER_REQUEST_TIMEOUT_MS } from "@/lib/ai-providers/transport";

export type PlatformProviderProbeServiceErrorCode =
  | "PLATFORM_PROVIDER_PROBE_INVALID_INPUT"
  | "PLATFORM_PROVIDER_PROBE_ADMIN_REQUIRED"
  | "PLATFORM_PROVIDER_PROBE_PROVIDER_NOT_FOUND"
  | "PLATFORM_PROVIDER_PROBE_PROVIDER_DISABLED"
  | "PLATFORM_PROVIDER_PROBE_CANONICAL_ENDPOINT_REQUIRED"
  | "PLATFORM_PROVIDER_PROBE_CONFIGURATION_CONFLICT"
  | "PLATFORM_PROVIDER_PROBE_BUDGET_REQUIRED"
  | "PLATFORM_PROVIDER_PROBE_BUDGET_EXHAUSTED"
  | "PLATFORM_PROVIDER_PROBE_IDEMPOTENCY_CONFLICT"
  | "PLATFORM_PROVIDER_PROBE_IN_PROGRESS"
  | "PLATFORM_PROVIDER_PROBE_RECONCILIATION_REQUIRED"
  | "PLATFORM_PROVIDER_PROBE_PROVIDER_UNAVAILABLE"
  | "PLATFORM_PROVIDER_PROBE_PROVIDER_AUTH_FAILED"
  | "PLATFORM_PROVIDER_PROBE_PROVIDER_RATE_LIMITED"
  | "PLATFORM_PROVIDER_PROBE_PROVIDER_REJECTED"
  | "PLATFORM_PROVIDER_PROBE_PROVIDER_INVALID_RESPONSE"
  | "PLATFORM_PROVIDER_PROBE_PROVIDER_RESPONSE_TOO_LARGE"
  | "PLATFORM_PROVIDER_PROBE_PROVIDER_TIMEOUT"
  | "PLATFORM_PROVIDER_PROBE_PROVIDER_EMBEDDING_UNSUPPORTED"
  | "PLATFORM_PROVIDER_PROBE_PROVIDER_VISION_UNSUPPORTED"
  | "PLATFORM_PROVIDER_PROBE_RECONCILED_NO_DISPATCH"
  | "PLATFORM_PROVIDER_PROBE_RECONCILIATION_HOLD";

export class PlatformProviderProbeServiceError extends Error {
  constructor(readonly code: PlatformProviderProbeServiceErrorCode) {
    super(code);
    this.name = "PlatformProviderProbeServiceError";
  }
}

export const PLATFORM_PROVIDER_PROBE_MAX_BODY_BYTES = 4 * 1024;
export const PLATFORM_PROVIDER_PROBE_MAX_UNITS = 3;
export const PLATFORM_PROVIDER_PROBE_LEASE_MS = PROVIDER_REQUEST_TIMEOUT_MS * PLATFORM_PROVIDER_PROBE_MAX_UNITS + 15_000;
export const PLATFORM_PROVIDER_PROBE_MAX_BUDGET_UNITS = 10_000;
export const PLATFORM_PROVIDER_PROBE_MAX_BUDGET_DURATION_MS = 90 * 24 * 60 * 60 * 1_000;
