export const SYSTEM_AUDIT_SOURCES = [
  "platformDefaultAiRoute",
  "membershipSubscription",
  "accountAccess",
  "membershipAccess",
  "workspaceInvitation",
  "mcpToolAttestation",
  "projectAiProviderDelegation",
  "projectGitRepositoryDelegation",
  "projectGitManualRun",
  "projectMcpConnectionDelegation",
  "projectMcpToolGrantLedger",
  "projectMcpActionApproval",
  "projectMcpActionRuntime",
  "aiRuntime",
  "webAiConfirmation",
  "platformProviderProbe",
  "platformGrantOfferPolicy",
] as const;

export type SystemAuditSource = (typeof SYSTEM_AUDIT_SOURCES)[number];

export const SYSTEM_AUDIT_SOURCE_LABELS: Readonly<Record<SystemAuditSource, string>> = {
  platformDefaultAiRoute: "平台默认路由",
  membershipSubscription: "会员资格",
  accountAccess: "账号状态",
  membershipAccess: "成员访问",
  workspaceInvitation: "工作区邀请",
  mcpToolAttestation: "MCP 工具认证",
  projectAiProviderDelegation: "项目 AI 委托",
  projectGitRepositoryDelegation: "项目 Git 委托",
  projectGitManualRun: "项目 Git 手动运行",
  projectMcpConnectionDelegation: "项目 MCP 委托",
  projectMcpToolGrantLedger: "项目 MCP 工具授权",
  projectMcpActionApproval: "项目 MCP 动作审批",
  projectMcpActionRuntime: "项目 MCP 动作运行",
  aiRuntime: "AI 运行时",
  webAiConfirmation: "Web AI 确认",
  platformProviderProbe: "平台连接探测",
  platformGrantOfferPolicy: "平台赠送策略",
};

export const SYSTEM_AUDIT_ACTIONS = [
  "draftCreated",
  "draftUpdated",
  "validated",
  "activated",
  "retired",
  "grant",
  "extend",
  "revoke",
  "disabled",
  "restored",
  "migrationQuarantined",
  "confirmed",
  "bootstrapConfirmed",
  "created",
  "accepted",
  "attested",
  "proposed",
  "ownerConfirmed",
  "rejected",
  "revoked",
  "expired",
  "platformSelected",
  "personalSelected",
  "selectionUpdated",
  "granted",
  "requested",
  "admitted",
  "dispatched",
  "succeeded",
  "failed",
  "unknown",
  "conflict",
  "approved",
  "cancelled",
  "reserved",
  "invalidated",
  "policyCreated",
  "policyAdvanced",
  "grantIssued",
  "grantRevoked",
  "preflightRejected",
  "scannerRejected",
  "budgetRejected",
  "runCreated",
  "runClaimed",
  "dispatchSent",
  "runSucceeded",
  "runFailed",
  "runUnknown",
  "runCancelled",
  "attemptSucceeded",
  "attemptFailed",
  "attemptUnknown",
  "attemptCancelled",
  "memoryExtract",
  "memoryIndex",
  "memorySearch",
  "memoryAnswer",
  "assetRecognize",
  "intelligenceBrief",
  "intelligenceAgent",
  "settled",
  "released",
  "held",
] as const;

export type SystemAuditAction = (typeof SYSTEM_AUDIT_ACTIONS)[number];

export const SYSTEM_AUDIT_ACTION_LABELS: Readonly<Record<SystemAuditAction, string>> = {
  draftCreated: "创建草稿",
  draftUpdated: "更新草稿",
  validated: "验证",
  activated: "启用",
  retired: "退役",
  grant: "发放",
  extend: "延期",
  revoke: "撤销",
  disabled: "已停用",
  restored: "已恢复",
  migrationQuarantined: "迁移隔离",
  confirmed: "确认",
  bootstrapConfirmed: "引导确认",
  created: "创建",
  accepted: "接受",
  attested: "认证",
  proposed: "提议",
  ownerConfirmed: "所有者确认",
  rejected: "拒绝",
  revoked: "撤销",
  expired: "过期",
  platformSelected: "选择平台路由",
  personalSelected: "选择个人路由",
  selectionUpdated: "更新路由选择",
  granted: "授权",
  requested: "请求",
  admitted: "准入",
  dispatched: "已派发",
  succeeded: "成功",
  failed: "失败",
  unknown: "未知",
  conflict: "冲突",
  approved: "批准",
  cancelled: "已取消",
  reserved: "预留",
  settled: "已结算",
  released: "已释放",
  held: "待人工核对",
  invalidated: "已失效",
  policyCreated: "创建策略",
  policyAdvanced: "推进策略",
  grantIssued: "发放 AI 授权",
  grantRevoked: "撤销 AI 授权",
  preflightRejected: "预检拒绝",
  scannerRejected: "扫描拒绝",
  budgetRejected: "额度拒绝",
  runCreated: "创建运行",
  runClaimed: "领取运行",
  dispatchSent: "发送调用",
  runSucceeded: "运行成功",
  runFailed: "运行失败",
  runUnknown: "运行结果未知",
  runCancelled: "运行取消",
  attemptSucceeded: "尝试成功",
  attemptFailed: "尝试失败",
  attemptUnknown: "尝试结果未知",
  attemptCancelled: "尝试取消",
  memoryExtract: "记忆抽取",
  memoryIndex: "记忆索引",
  memorySearch: "记忆检索",
  memoryAnswer: "记忆问答",
  assetRecognize: "资产识别",
  intelligenceBrief: "项目简报",
  intelligenceAgent: "项目智能体",
};

export const SYSTEM_AUDIT_RESULTS = [
  "applied",
  "pending",
  "disabled",
  "restored",
  "rejected",
  "revoked",
  "expired",
  "failed",
  "cancelled",
  "invalidated",
  "unknown",
] as const;

export type SystemAuditResult = (typeof SYSTEM_AUDIT_RESULTS)[number];

export const SYSTEM_AUDIT_RESULT_LABELS: Readonly<Record<SystemAuditResult, string>> = {
  applied: "已生效",
  pending: "待处理",
  disabled: "已停用",
  restored: "已恢复",
  rejected: "已拒绝",
  revoked: "已撤销",
  expired: "已过期",
  failed: "失败",
  cancelled: "已取消",
  invalidated: "已失效",
  unknown: "未分类",
};

export const SYSTEM_AUDIT_SOURCE_OPTIONS: ReadonlyArray<readonly [string, string]> = [
  ["", "全部来源"],
  ...SYSTEM_AUDIT_SOURCES.map((source) => [source, SYSTEM_AUDIT_SOURCE_LABELS[source]] as const),
];

export const SYSTEM_AUDIT_ACTION_OPTIONS: ReadonlyArray<readonly [string, string]> = [
  ["", "全部动作"],
  ...SYSTEM_AUDIT_ACTIONS.map((action) => [action, SYSTEM_AUDIT_ACTION_LABELS[action]] as const),
];

export const SYSTEM_AUDIT_RESULT_OPTIONS: ReadonlyArray<readonly [string, string]> = [
  ["", "全部结果"],
  ...SYSTEM_AUDIT_RESULTS.map((result) => [result, SYSTEM_AUDIT_RESULT_LABELS[result]] as const),
];

export const SYSTEM_AUDIT_ALLOWED_ACTIONS_BY_SOURCE: Readonly<Record<SystemAuditSource, readonly SystemAuditAction[]>> = {
  platformDefaultAiRoute: ["draftCreated", "draftUpdated", "validated", "activated", "retired"],
  membershipSubscription: ["grant", "extend", "revoke"],
  accountAccess: ["disabled", "restored"],
  membershipAccess: ["migrationQuarantined", "confirmed", "revoked", "bootstrapConfirmed"],
  workspaceInvitation: ["created", "accepted", "revoked"],
  mcpToolAttestation: ["attested", "revoked"],
  projectAiProviderDelegation: ["proposed", "ownerConfirmed", "activated", "rejected", "revoked", "expired", "platformSelected", "personalSelected", "selectionUpdated"],
  projectGitRepositoryDelegation: ["proposed", "ownerConfirmed", "activated", "rejected", "revoked", "expired"],
  projectGitManualRun: ["requested", "admitted", "dispatched", "succeeded", "failed", "unknown", "conflict"],
  projectMcpConnectionDelegation: ["proposed", "ownerConfirmed", "activated", "rejected", "revoked", "expired"],
  projectMcpToolGrantLedger: ["granted", "revoked"],
  projectMcpActionApproval: ["proposed", "approved", "rejected", "cancelled"],
  projectMcpActionRuntime: ["reserved", "succeeded", "failed", "unknown", "expired", "invalidated"],
  aiRuntime: ["policyCreated", "policyAdvanced", "grantIssued", "grantRevoked", "preflightRejected", "scannerRejected", "budgetRejected", "runCreated", "runClaimed", "dispatchSent", "runSucceeded", "runFailed", "runUnknown", "runCancelled", "attemptSucceeded", "attemptFailed", "attemptUnknown", "attemptCancelled"],
  webAiConfirmation: ["memoryExtract", "memoryIndex", "memorySearch", "memoryAnswer", "assetRecognize", "intelligenceBrief", "intelligenceAgent"],
  platformProviderProbe: ["reserved", "dispatched", "settled", "released", "held", "rejected"],
  platformGrantOfferPolicy: ["created", "activated", "retired"],
};

export const SYSTEM_AUDIT_ALLOWED_RESULTS_BY_SOURCE: Readonly<Record<SystemAuditSource, readonly SystemAuditResult[]>> = {
  platformDefaultAiRoute: ["applied"],
  membershipSubscription: ["applied", "revoked"],
  accountAccess: ["disabled", "restored"],
  membershipAccess: ["applied", "pending", "revoked"],
  workspaceInvitation: ["pending", "applied", "revoked"],
  mcpToolAttestation: ["applied", "revoked"],
  projectAiProviderDelegation: ["applied", "pending", "rejected", "revoked", "expired"],
  projectGitRepositoryDelegation: ["applied", "pending", "rejected", "revoked", "expired"],
  projectGitManualRun: ["applied", "pending", "rejected", "failed", "unknown"],
  projectMcpConnectionDelegation: ["applied", "pending", "rejected", "revoked", "expired"],
  projectMcpToolGrantLedger: ["applied", "revoked"],
  projectMcpActionApproval: ["applied", "pending", "rejected", "cancelled"],
  projectMcpActionRuntime: ["applied", "pending", "failed", "unknown", "expired", "invalidated"],
  aiRuntime: ["applied", "pending", "rejected", "revoked", "failed", "cancelled", "unknown"],
  webAiConfirmation: ["applied", "pending", "expired"],
  platformProviderProbe: ["applied", "pending", "rejected", "unknown"],
  platformGrantOfferPolicy: ["applied", "pending", "revoked"],
};
