const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu;

export const MATERIAL_KIND_VALUES = ["all", "document", "screenshot", "github", "git", "web", "manual"] as const;
export type MaterialKind = (typeof MATERIAL_KIND_VALUES)[number];

export const REVIEW_TYPE_VALUES = ["all", "decision", "progress", "issue", "risk"] as const;
export type ReviewType = (typeof REVIEW_TYPE_VALUES)[number];

const MATERIALS_QUERY_KEYS = new Set(["search", "kind", "page", "focus"]);

export function isMaterialKind(value: string | null | undefined): value is MaterialKind {
  return value !== null && value !== undefined && MATERIAL_KIND_VALUES.includes(value as MaterialKind);
}

export function parseMaterialKind(value: string | null | undefined): MaterialKind {
  return isMaterialKind(value) ? value : "all";
}

export function isReviewType(value: string | null | undefined): value is ReviewType {
  return value !== null && value !== undefined && REVIEW_TYPE_VALUES.includes(value as ReviewType);
}

export function parseReviewType(value: string | null | undefined): ReviewType {
  return isReviewType(value) ? value : "all";
}

export function parseMaterialsPage(value: string | null | undefined): number {
  if (!value || !/^\d+$/u.test(value)) return 1;
  const page = Number(value);
  return Number.isSafeInteger(page) && page > 0 ? page : 1;
}

export function buildMaterialsReturnTo(
  projectId: string,
  input: { search?: string; kind?: MaterialKind; page?: number; focus?: string },
): string {
  const params = new URLSearchParams();
  const search = input.search?.trim();
  if (search) params.set("search", search.slice(0, 200));
  params.set("kind", parseMaterialKind(input.kind));
  if (input.page && Number.isSafeInteger(input.page) && input.page > 1) params.set("page", String(input.page));
  if (input.focus && UUID_PATTERN.test(input.focus)) params.set("focus", input.focus);
  const query = params.toString();
  return `/projects/${encodeURIComponent(projectId)}/materials${query ? `?${query}` : ""}`;
}

/**
 * Accept only a same-project materials path generated by this workspace.
 * The returned value is rebuilt from a small allowlist so unknown query keys
 * and open-redirect payloads never reach router navigation.
 */
export function safeMaterialsReturnTo(projectId: string, value: string | null | undefined): string | null {
  if (!value || value.length > 2_048 || value.includes("\\") || value.includes("://") || value.startsWith("//")) return null;

  let parsed: URL;
  try {
    parsed = new URL(value, "https://ai-project-os.invalid");
  } catch {
    return null;
  }

  const expectedPath = `/projects/${projectId}/materials`;
  if (parsed.origin !== "https://ai-project-os.invalid" || parsed.pathname !== expectedPath || parsed.hash) return null;

  for (const key of parsed.searchParams.keys()) {
    if (!MATERIALS_QUERY_KEYS.has(key)) return null;
    if (parsed.searchParams.getAll(key).length !== 1) return null;
  }

  const kind = parseMaterialKind(parsed.searchParams.get("kind"));
  if (parsed.searchParams.has("kind") && parsed.searchParams.get("kind") !== kind) return null;
  const pageValue = parsed.searchParams.get("page");
  const page = parseMaterialsPage(pageValue);
  if (pageValue !== null && pageValue !== String(page)) return null;
  const focus = parsed.searchParams.get("focus");
  if (focus !== null && !UUID_PATTERN.test(focus)) return null;

  return buildMaterialsReturnTo(projectId, {
    search: parsed.searchParams.get("search") ?? undefined,
    kind,
    page,
    focus: focus ?? undefined,
  });
}

export function isAddSourceView(value: string | null | undefined): boolean {
  return value === "add";
}
