-- Clean-slate 0.2 AI provider model.
--
-- This is a forward migration.  The application has no production users yet,
-- but a migration must still fail closed if a legacy row is present instead of
-- silently discarding it.  Git/MCP ownership data and all AI runtime evidence
-- are intentionally outside this migration.

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
      FROM "AppUser"
     WHERE "role"::text = 'member'
  ) THEN
    RAISE EXCEPTION
      'CLEAN_SLATE_PRECONDITION_FAILED: AppUserRole.member rows remain'
      USING ERRCODE = 'check_violation';
  END IF;

  IF EXISTS (
    SELECT 1
      FROM "AiProviderConnection"
     WHERE "scope"::text = 'workspace'
        OR "workspaceId" IS NOT NULL
  ) THEN
    RAISE EXCEPTION
      'CLEAN_SLATE_PRECONDITION_FAILED: workspace AI provider rows remain'
      USING ERRCODE = 'check_violation';
  END IF;

  IF to_regclass('"ProjectAiRoute"') IS NOT NULL
     AND EXISTS (SELECT 1 FROM "ProjectAiRoute") THEN
    RAISE EXCEPTION
      'CLEAN_SLATE_PRECONDITION_FAILED: ProjectAiRoute rows remain'
      USING ERRCODE = 'check_violation';
  END IF;

  IF to_regclass('"ProjectAiRouteRevision"') IS NOT NULL
     AND EXISTS (SELECT 1 FROM "ProjectAiRouteRevision") THEN
    RAISE EXCEPTION
      'CLEAN_SLATE_PRECONDITION_FAILED: ProjectAiRouteRevision rows remain'
      USING ERRCODE = 'check_violation';
  END IF;

  IF to_regclass('"AiProviderOwnershipAudit"') IS NOT NULL
     AND EXISTS (SELECT 1 FROM "AiProviderOwnershipAudit") THEN
    RAISE EXCEPTION
      'CLEAN_SLATE_PRECONDITION_FAILED: AiProviderOwnershipAudit rows remain'
      USING ERRCODE = 'check_violation';
  END IF;
END;
$$;

-- Remove deferred guards whose old bodies read the provider workspace tuple.
-- The remaining platform/user guards are recreated below or retained with
-- their personal owner epoch semantics.
DROP TRIGGER IF EXISTS "AiProviderConnection_workspace_membership_guard" ON "AiProviderConnection";
DROP TRIGGER IF EXISTS "AiProviderConnection_workspace_owner_guard" ON "AiProviderConnection";
DROP TRIGGER IF EXISTS "WorkspaceMembership_ai_provider_membership_guard" ON "WorkspaceMembership";
DROP TRIGGER IF EXISTS "WorkspaceMembership_provider_owner_integrity_guard" ON "WorkspaceMembership";
DROP TRIGGER IF EXISTS "AiProviderConnection_identity_guard" ON "AiProviderConnection";

-- Rebuild-bound enum values are also referenced by PL/pgSQL trigger plans and
-- trigger-owned dependency checks.  Remove the exact trigger objects first;
-- they are recreated after AiProviderScope has its replacement type.  This is
-- deliberately an allow-list: no CASCADE is used and unrelated Git/MCP or
-- project lifecycle triggers remain installed throughout the migration.
DROP TRIGGER IF EXISTS "AiProviderConnection_personal_epoch_guard" ON "AiProviderConnection";
DROP TRIGGER IF EXISTS "PAD_provider_global_lock" ON "AiProviderConnection";
DROP TRIGGER IF EXISTS "PAD_provider_dependent_guard" ON "AiProviderConnection";
DROP TRIGGER IF EXISTS "MemoryPersonalProviderInvalidationGuard" ON "AiProviderConnection";
DROP TRIGGER IF EXISTS "ProjectAiProviderDelegation_active_integrity_guard" ON "ProjectAiProviderDelegation";
DROP TRIGGER IF EXISTS "ProjectAiEffectiveRouteSelection_integrity_guard" ON "ProjectAiEffectiveRouteSelection";
DROP TRIGGER IF EXISTS "ProjectAiProviderDelegation_personal_epoch_guard" ON "ProjectAiProviderDelegation";
DROP TRIGGER IF EXISTS "ProjectAiEffectiveRouteSelection_personal_epoch_guard" ON "ProjectAiEffectiveRouteSelection";
DROP TRIGGER IF EXISTS "PlatformTokenReservation_runtime_evidence_guard" ON "PlatformTokenReservation";
DROP TRIGGER IF EXISTS "ProviderCallAudit_runtime_evidence_guard" ON "ProviderCallAudit";
DROP TRIGGER IF EXISTS "WebAiGrant_personal_runtime_evidence_guard" ON "WebAiGrant";
DROP TRIGGER IF EXISTS "ProviderCallAudit_personal_runtime_evidence_guard" ON "ProviderCallAudit";
DROP TRIGGER IF EXISTS "MemoryIndexGeneration_personal_evidence_guard" ON "MemoryIndexGeneration";
DROP TRIGGER IF EXISTS "MemoryIndexPointer_personal_evidence_guard" ON "MemoryIndexPointer";

-- Rewrite live trigger/function definitions before dropping the columns.  The
-- function bodies are generated by PostgreSQL from the last applied schema,
-- so this keeps the forward migration valid for every supported clean-slate
-- starting database without editing historical migrations.
DO $$
DECLARE
  function_row RECORD;
  function_definition TEXT;
BEGIN
  FOR function_row IN
    SELECT p.oid
      FROM pg_proc AS p
      JOIN pg_namespace AS n ON n.oid = p.pronamespace
     WHERE n.nspname = 'public'
       AND p.prokind = 'f'
       AND p.proname = ANY (ARRAY[
         'personal_memory_frozen_evidence_valid',
         'personal_memory_frozen_evidence_valid_without_epoch',
         'personal_memory_upstream_invalidation_guard',
         'personal_memory_index_live_evidence_valid',
         'personal_memory_index_live_evidence_valid_without_epoch',
         'personal_ai_grant_consistency_guard',
         'personal_ai_provider_call_consistency_guard',
         'runtime_ai_evidence_consistency_guard',
         'project_ai_provider_delegation_active_integrity_guard',
         'project_ai_effective_route_selection_integrity_guard',
         'project_ai_provider_connection_dependent_guard',
         'personal_ai_provider_connection_epoch_guard',
         'personal_ai_delegation_epoch_guard',
         'personal_ai_selection_epoch_guard'
       ])
  LOOP
    function_definition := pg_get_functiondef(function_row.oid);
    function_definition := regexp_replace(
      function_definition,
      E'\\s+OR OLD\\."ownershipState"\\s+IS DISTINCT FROM\\s+NEW\\."ownershipState"',
      '',
      'g'
    );
    function_definition := regexp_replace(
      function_definition,
      E'\\s+OR OLD\\."workspaceId"\\s+IS DISTINCT FROM\\s+NEW\\."workspaceId"',
      '',
      'g'
    );
    function_definition := regexp_replace(
      function_definition,
      E'\\s+AND provider\\."workspaceId"\\s+IS NULL',
      '',
      'g'
    );
    function_definition := regexp_replace(
      function_definition,
      E'\\s+AND provider\\."ownershipState"\\s*=\\s*''confirmed''',
      '',
      'g'
    );
    function_definition := regexp_replace(
      function_definition,
      E'\\s*,\\s*"ownershipState"\\s+AS\\s+ownership_state\\s*,',
      ',',
      'g'
    );
    function_definition := replace(
      function_definition,
      '"scope" AS scope, "ownershipState" AS ownership_state, ',
      '"scope" AS scope, '
    );
    function_definition := replace(
      function_definition,
      'provider_row.ownership_state IS DISTINCT FROM ''confirmed'' OR ',
      ''
    );
    function_definition := regexp_replace(
      function_definition,
      E'provider_row\\.ownership_state\\s+IS DISTINCT FROM\\s+''confirmed''\\s+OR\\s+',
      '',
      'g'
    );
    EXECUTE function_definition;
  END LOOP;
END;
$$;

-- Fail closed if a historical function shape escaped the rewrite.  This
-- check runs while the legacy columns still exist, so its diagnostic remains
-- actionable instead of surfacing later as a missing-column error.
DO $$
DECLARE
  function_row RECORD;
  function_definition TEXT;
BEGIN
  FOR function_row IN
    SELECT p.oid, p.proname
      FROM pg_proc AS p
      JOIN pg_namespace AS n ON n.oid = p.pronamespace
     WHERE n.nspname = 'public'
       AND p.prokind = 'f'
       AND p.proname = ANY (ARRAY[
         'personal_memory_frozen_evidence_valid',
         'personal_memory_frozen_evidence_valid_without_epoch',
         'personal_memory_upstream_invalidation_guard',
         'personal_memory_index_live_evidence_valid',
         'personal_memory_index_live_evidence_valid_without_epoch',
         'personal_ai_grant_consistency_guard',
         'personal_ai_provider_call_consistency_guard',
         'runtime_ai_evidence_consistency_guard',
         'project_ai_provider_delegation_active_integrity_guard',
         'project_ai_effective_route_selection_integrity_guard',
         'project_ai_provider_connection_dependent_guard'
       ])
  LOOP
    function_definition := pg_get_functiondef(function_row.oid);
    IF function_definition ~ '"workspaceId"|"ownershipState"' THEN
      RAISE EXCEPTION
        'CLEAN_SLATE_PRECONDITION_FAILED: stale AI provider function % references removed columns',
        function_row.proname
        USING ERRCODE = 'check_violation';
    END IF;
  END LOOP;
END;
$$;

-- The old membership trigger function is no longer meaningful once provider
-- ownership is limited to platform or user.  Drop it rather than leaving a
-- callable function that references removed columns.
DROP FUNCTION IF EXISTS "ai_provider_workspace_membership_guard"();
DROP FUNCTION IF EXISTS "WorkspaceMembership_provider_owner_integrity_guard"();
DROP FUNCTION IF EXISTS "AiProviderConnection_workspace_owner_guard"();

DROP INDEX IF EXISTS "AiProviderConnection_scope_workspaceId_status_idx";
DROP INDEX IF EXISTS "AiProviderConnection_ownerUserId_ownershipState_updatedAt_idx";
-- These scope-aware indexes were built against the old AiProviderScope enum.
-- Partial predicates retain a typed enum constant, so they must be removed
-- before ALTER COLUMN ... TYPE; otherwise PostgreSQL attempts to compare the
-- replacement enum with the old enum (42883).  The clean schema only keeps
-- the non-unique scope/name lookup below, recreated after the type swap.
DROP INDEX IF EXISTS "AiProviderConnection_legacy_scope_name_key";
DROP INDEX IF EXISTS "AiProviderConnection_user_name_key";
DROP INDEX IF EXISTS "AiProviderConnection_scope_name_idx";
ALTER TABLE "AiProviderConnection"
  DROP CONSTRAINT IF EXISTS "AiProviderConnection_workspaceId_fkey",
  DROP CONSTRAINT IF EXISTS "AiProviderConnection_scope_check",
  DROP CONSTRAINT IF EXISTS "AiProviderConnection_owner_scope_check";

-- Some early clean-slate development databases were created from the same
-- ownership shape with Prisma's generated constraint name
-- AiProviderConnection_owner_scope_check.  Keep the historical names above
-- explicit, then remove any remaining CHECK constraint on this table only when
-- its expression directly mentions a field that is about to be removed.  This
-- is an exact, non-CASCADE drop and prevents an old enum-typed CHECK from being
-- coerced while AiProviderScope is rebuilt.
DO $$
DECLARE
  constraint_row RECORD;
  constraint_definition TEXT;
BEGIN
  FOR constraint_row IN
    SELECT conname, oid
      FROM pg_constraint
     WHERE conrelid = 'public."AiProviderConnection"'::regclass
       AND contype = 'c'
  LOOP
    constraint_definition := pg_get_constraintdef(constraint_row.oid);
    IF constraint_definition ~ '"scope"'
       OR constraint_definition ~ '"workspaceId"'
       OR constraint_definition ~ '"ownershipState"'
    THEN
      EXECUTE format(
        'ALTER TABLE "AiProviderConnection" DROP CONSTRAINT %I',
        constraint_row.conname
      );
    END IF;
  END LOOP;
END;
$$;

ALTER TABLE "AiProviderConnection"
  DROP COLUMN IF EXISTS "workspaceId",
  DROP COLUMN IF EXISTS "ownershipState";

-- Drop the legacy route/audit tables before rebuilding AiProviderScope: the
-- audit table still has columns typed with the old enum at this point.
DROP TABLE IF EXISTS "AiProviderOwnershipAudit";
DROP TYPE IF EXISTS "AiProviderOwnershipAuditAction";
DROP TABLE IF EXISTS "ProjectAiRouteRevision";
DROP TABLE IF EXISTS "ProjectAiRoute";

-- PostgreSQL enums cannot remove a label in place.  Rebuild both affected
-- enums with replacement types, preserving the enum names consumed by Prisma.
CREATE TYPE "AiProviderScope_clean" AS ENUM ('platform', 'user');
ALTER TABLE "AiProviderConnection"
  ALTER COLUMN "scope" DROP DEFAULT,
  ALTER COLUMN "scope" TYPE "AiProviderScope_clean"
    USING "scope"::text::"AiProviderScope_clean";
DROP TYPE "AiProviderScope";
ALTER TYPE "AiProviderScope_clean" RENAME TO "AiProviderScope";
ALTER TABLE "AiProviderConnection"
  ALTER COLUMN "scope" SET DEFAULT 'platform';

CREATE INDEX "AiProviderConnection_scope_name_idx"
  ON "AiProviderConnection"("scope", "name");

CREATE TYPE "AppUserRole_clean" AS ENUM ('admin', 'user');
ALTER TABLE "AppUser"
  ALTER COLUMN "role" DROP DEFAULT,
  ALTER COLUMN "role" TYPE "AppUserRole_clean"
    USING "role"::text::"AppUserRole_clean";
DROP TYPE "AppUserRole";
ALTER TYPE "AppUserRole_clean" RENAME TO "AppUserRole";
ALTER TABLE "AppUser"
  ALTER COLUMN "role" SET DEFAULT 'user';

-- Recompile the clean function bodies after both enum replacements.  This
-- refreshes any PL/pgSQL plans that compare provider scope before the guards
-- are attached again, while preserving the existing function semantics.
DO $$
DECLARE
  function_row RECORD;
BEGIN
  FOR function_row IN
    SELECT p.oid
      FROM pg_proc AS p
      JOIN pg_namespace AS n ON n.oid = p.pronamespace
     WHERE n.nspname = 'public'
       AND p.prokind = 'f'
       AND p.proname = ANY (ARRAY[
         'personal_memory_frozen_evidence_valid',
         'personal_memory_frozen_evidence_valid_without_epoch',
         'personal_memory_upstream_invalidation_guard',
         'personal_memory_index_live_evidence_valid',
         'personal_memory_index_live_evidence_valid_without_epoch',
         'personal_ai_grant_consistency_guard',
         'personal_ai_provider_call_consistency_guard',
         'runtime_ai_evidence_consistency_guard',
         'project_ai_provider_delegation_active_integrity_guard',
         'project_ai_effective_route_selection_integrity_guard',
         'project_ai_provider_connection_dependent_guard',
         'personal_ai_provider_connection_epoch_guard',
         'personal_ai_delegation_epoch_guard',
         'personal_ai_selection_epoch_guard'
       ])
  LOOP
    EXECUTE pg_get_functiondef(function_row.oid);
  END LOOP;
END;
$$;

ALTER TABLE "AiProviderConnection"
  ADD CONSTRAINT "AiProviderConnection_scope_check"
  CHECK (("scope" = 'platform' AND "ownerUserId" IS NULL)
      OR ("scope" = 'user' AND "ownerUserId" IS NOT NULL));

-- Platform and personal provider identity is immutable.  Configuration and
-- credential rotation remain supported; only scope/owner/credential identity
-- is fenced.
CREATE OR REPLACE FUNCTION "ai_provider_connection_identity_guard"()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF OLD."scope" IS DISTINCT FROM NEW."scope"
     OR OLD."ownerUserId" IS DISTINCT FROM NEW."ownerUserId"
     OR OLD."credentialId" IS DISTINCT FROM NEW."credentialId"
  THEN
    RAISE EXCEPTION 'AI_PROVIDER_OWNERSHIP_IMMUTABLE'
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "AiProviderConnection_identity_guard"
BEFORE UPDATE ON "AiProviderConnection"
FOR EACH ROW EXECUTE FUNCTION "ai_provider_connection_identity_guard"();

-- Enforce the two legal ownership shapes independently of ORM validation.
CREATE OR REPLACE FUNCTION "AiProviderConnection_owner_guard"()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW."scope" = 'platform' AND NEW."ownerUserId" IS NOT NULL THEN
    RAISE EXCEPTION 'platform provider cannot have an owner'
      USING ERRCODE = 'check_violation';
  END IF;
  IF NEW."scope" = 'user' AND NEW."ownerUserId" IS NULL THEN
    RAISE EXCEPTION 'user provider requires an owner'
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "AiProviderConnection_owner_guard"
BEFORE INSERT OR UPDATE ON "AiProviderConnection"
FOR EACH ROW EXECUTE FUNCTION "AiProviderConnection_owner_guard"();

-- Reattach the platform/user runtime and delegation guards only after the
-- replacement enum is active.  These definitions intentionally preserve the
-- historical trigger timing and deferrability; only their clean function
-- bodies were recompiled above.
CREATE TRIGGER "AiProviderConnection_personal_epoch_guard"
BEFORE INSERT OR UPDATE ON "AiProviderConnection"
FOR EACH ROW EXECUTE FUNCTION "personal_ai_provider_connection_epoch_guard"();

CREATE TRIGGER "PAD_provider_global_lock"
BEFORE INSERT OR UPDATE OR DELETE ON "AiProviderConnection"
FOR EACH STATEMENT EXECUTE FUNCTION "project_ai_provider_delegation_global_lock"();

CREATE CONSTRAINT TRIGGER "PAD_provider_dependent_guard"
AFTER UPDATE OR DELETE ON "AiProviderConnection"
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION "project_ai_provider_connection_dependent_guard"();

CREATE CONSTRAINT TRIGGER "MemoryPersonalProviderInvalidationGuard"
AFTER UPDATE OR DELETE ON "AiProviderConnection"
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION "personal_memory_upstream_invalidation_guard"();

CREATE CONSTRAINT TRIGGER "ProjectAiProviderDelegation_active_integrity_guard"
AFTER INSERT OR UPDATE ON "ProjectAiProviderDelegation"
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION "project_ai_provider_delegation_active_integrity_guard"();

CREATE CONSTRAINT TRIGGER "ProjectAiEffectiveRouteSelection_integrity_guard"
AFTER INSERT OR UPDATE ON "ProjectAiEffectiveRouteSelection"
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION "project_ai_effective_route_selection_integrity_guard"();

CREATE CONSTRAINT TRIGGER "ProjectAiProviderDelegation_personal_epoch_guard"
AFTER INSERT OR UPDATE ON "ProjectAiProviderDelegation"
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION "personal_ai_delegation_epoch_guard"();

CREATE CONSTRAINT TRIGGER "ProjectAiEffectiveRouteSelection_personal_epoch_guard"
AFTER INSERT OR UPDATE ON "ProjectAiEffectiveRouteSelection"
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION "personal_ai_selection_epoch_guard"();

CREATE CONSTRAINT TRIGGER "PlatformTokenReservation_runtime_evidence_guard"
AFTER INSERT OR UPDATE ON "PlatformTokenReservation"
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION "runtime_ai_evidence_consistency_guard"();

CREATE CONSTRAINT TRIGGER "ProviderCallAudit_runtime_evidence_guard"
AFTER INSERT OR UPDATE ON "ProviderCallAudit"
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION "runtime_ai_evidence_consistency_guard"();

CREATE CONSTRAINT TRIGGER "WebAiGrant_personal_runtime_evidence_guard"
AFTER INSERT OR UPDATE ON "WebAiGrant"
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION "personal_ai_grant_consistency_guard"();

CREATE CONSTRAINT TRIGGER "ProviderCallAudit_personal_runtime_evidence_guard"
AFTER INSERT OR UPDATE ON "ProviderCallAudit"
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION "personal_ai_provider_call_consistency_guard"();

CREATE CONSTRAINT TRIGGER "MemoryIndexGeneration_personal_evidence_guard"
AFTER INSERT OR UPDATE OR DELETE ON "MemoryIndexGeneration"
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION "personal_memory_index_evidence_guard"();

CREATE CONSTRAINT TRIGGER "MemoryIndexPointer_personal_evidence_guard"
AFTER INSERT OR UPDATE ON "MemoryIndexPointer"
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION "personal_memory_index_pointer_evidence_guard"();

-- Catalog assertions make the enum dependency boundary explicit.  They fail
-- the migration if a legacy workspace trigger survives or if any recreated
-- clean guard was accidentally omitted.
DO $$
DECLARE
  stale_trigger TEXT;
  missing_trigger TEXT;
BEGIN
  SELECT format('%I on %I', expected.trigger_name, expected.relation_name)
    INTO stale_trigger
    FROM (VALUES
      ('AiProviderConnection_workspace_membership_guard', 'AiProviderConnection'),
      ('AiProviderConnection_workspace_owner_guard', 'AiProviderConnection'),
      ('WorkspaceMembership_ai_provider_membership_guard', 'WorkspaceMembership'),
      ('WorkspaceMembership_provider_owner_integrity_guard', 'WorkspaceMembership')
    ) AS expected(trigger_name, relation_name)
   WHERE EXISTS (
     SELECT 1
       FROM pg_trigger AS trigger_row
       JOIN pg_class AS relation_row ON relation_row.oid = trigger_row.tgrelid
       JOIN pg_namespace AS namespace_row ON namespace_row.oid = relation_row.relnamespace
      WHERE namespace_row.nspname = 'public'
        AND relation_row.relname = expected.relation_name
        AND trigger_row.tgname = expected.trigger_name
        AND NOT trigger_row.tgisinternal
   )
   LIMIT 1;
  IF stale_trigger IS NOT NULL THEN
    RAISE EXCEPTION 'CLEAN_SLATE_POSTCONDITION_FAILED: legacy trigger remains (%)', stale_trigger
      USING ERRCODE = 'check_violation';
  END IF;

  SELECT format('%I on %I', expected.trigger_name, expected.relation_name)
    INTO missing_trigger
    FROM (VALUES
      ('AiProviderConnection_personal_epoch_guard', 'AiProviderConnection'),
      ('PAD_provider_global_lock', 'AiProviderConnection'),
      ('PAD_provider_dependent_guard', 'AiProviderConnection'),
      ('MemoryPersonalProviderInvalidationGuard', 'AiProviderConnection'),
      ('ProjectAiProviderDelegation_active_integrity_guard', 'ProjectAiProviderDelegation'),
      ('ProjectAiEffectiveRouteSelection_integrity_guard', 'ProjectAiEffectiveRouteSelection'),
      ('ProjectAiProviderDelegation_personal_epoch_guard', 'ProjectAiProviderDelegation'),
      ('ProjectAiEffectiveRouteSelection_personal_epoch_guard', 'ProjectAiEffectiveRouteSelection'),
      ('PlatformTokenReservation_runtime_evidence_guard', 'PlatformTokenReservation'),
      ('ProviderCallAudit_runtime_evidence_guard', 'ProviderCallAudit'),
      ('WebAiGrant_personal_runtime_evidence_guard', 'WebAiGrant'),
      ('ProviderCallAudit_personal_runtime_evidence_guard', 'ProviderCallAudit'),
      ('MemoryIndexGeneration_personal_evidence_guard', 'MemoryIndexGeneration'),
      ('MemoryIndexPointer_personal_evidence_guard', 'MemoryIndexPointer')
    ) AS expected(trigger_name, relation_name)
   WHERE NOT EXISTS (
     SELECT 1
       FROM pg_trigger AS trigger_row
       JOIN pg_class AS relation_row ON relation_row.oid = trigger_row.tgrelid
       JOIN pg_namespace AS namespace_row ON namespace_row.oid = relation_row.relnamespace
      WHERE namespace_row.nspname = 'public'
        AND relation_row.relname = expected.relation_name
        AND trigger_row.tgname = expected.trigger_name
        AND NOT trigger_row.tgisinternal
   )
   LIMIT 1;
  IF missing_trigger IS NOT NULL THEN
    RAISE EXCEPTION 'CLEAN_SLATE_POSTCONDITION_FAILED: clean trigger missing (%)', missing_trigger
      USING ERRCODE = 'check_violation';
  END IF;
END;
$$;
